version: '3'

volumes:
  log-volume:
  sphinx-volume:
  db-volume:
  docstore-volume:
  assets-volume:

services:

  dbserver:
    depends_on:
         - mysql
         - redis
         - dbdaemon

    # Local Docker Registry
    # image: donald:5000/happychriss/ddocbox_base:latest

    image: happychriss/ddocbox_base:latest

    build:
      context: .
      dockerfile: Dockerfile

    links:
        - redis

    volumes:
      - ./DBServer:/docbox/DBServer
      - ./EntryPoint_DBServer:/init
      - ./DBServer/app_support/nginx.conf://etc/nginx/nginx.conf
      - /var/run/dbus:/var/run/dbus
      - sphinx-volume://docbox/SphinxFiles
      - log-volume://docbox/DBServer/log
      - docstore-volume://docbox/DBServer/public/docstore
      - assets-volume://docbox/DBServer/public/assets

    tmpfs:
      - /run
      - /tmp

    entrypoint:
      - /init/docker-entrypoint.sh

    ports:
      - "8082:8082"
      - "9292:9292"


    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379

  dbdaemon:
    depends_on:
         - mysql
         - redis

    #  image: donald:5000/happychriss/ddocbox_base:latest #use same image as for dbserver
    image: happychriss/ddocbox_base:latest #use same image as for dbserver

    links:
        - redis

    volumes:
      - ./DBDaemon:/docbox/DBDaemon
      - ./EntryPoint_DBDaemon:/init
      - /opt/vc/lib:/opt/vc/lib  #libmmal_core.so is used by unpaper ....
      - log-volume://docbox/DBDaemon/log

    tmpfs:
      - /run
      - /tmp

    devices:
      - /dev/bus/usb:/dev/bus/usb

    entrypoint:
#      - ./docker_rails/docker-entrypoint.sh
      - /init/docker-entrypoint.sh

    environment:
      - RAILS_ENV=production


  mysql:
    image: jsurf/rpi-mariadb
#    image: mariadb
    volumes:
      - db-volume:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: admin_docbox


  redis:
#    image: knjcode/rpi-redis
     image: "redis:alpine"