# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
#    And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  host: mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Docbox_development
  username: root
  password: admin_docbox



################### FAKE ##################################################################
production:
  host: mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Docbox_production
  username: root
  password: admin_docbox

