common: &common
    aws_s3_access_key: 'TOBEDONE'
    aws_s3_secret_key: 'TOBEDONE'

development:
    <<: *common
    aws_s3_bucket: 'development.ddocbox.com'
    aws_s3_db_bucket: 'development.ddocbox.db.com' ##### to be changed
    gpg_email_address: 'dev.cleandesk@googlemail.com'

test:
    <<: *common
    aws_s3_bucket: 'does not exists'
    gpg_email_address: 'does not exists'

production:
    <<: *common
    aws_s3_bucket: 'production.ddocbox.com' ##### to be changed
    aws_s3_db_bucket: 'production.ddocbox.db.com' ##### to be changed
    gpg_email_address: 'prod.cleandesk@googlemail.com'
